"""Add min_experience column

Revision ID: 29fba5a22dd7
Revises: 511e825b5af0
Create Date: 2025-10-10 18:26:15.879407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fba5a22dd7'
down_revision = '511e825b5af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_batches',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], )
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('package_min',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('package_max',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('batch')
        batch_op.drop_column('skills_required')
        batch_op.drop_column('experience_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_level', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('skills_required', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('batch', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('package_max',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('package_min',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('likes')
        batch_op.drop_column('min_experience')

    op.drop_table('job_batches')
    op.drop_table('batch')
    # ### end Alembic commands ###
