"""Initial migration

Revision ID: 511e825b5af0
Revises: 
Create Date: 2025-10-06 18:51:45.279014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511e825b5af0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('batch', sa.String(length=50), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=False),
    sa.Column('package_min', sa.Float(), nullable=False),
    sa.Column('package_max', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('skills_required', sa.String(length=500), nullable=False),
    sa.Column('apply_link', sa.String(length=500), nullable=False),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('admin')
    # ### end Alembic commands ###
