"""Add company_name column to job table

Revision ID: 6b2be8c982cd
Revises: db7d8d0c4cc6
Create Date: 2025-10-13 16:53:25.525941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b2be8c982cd'
down_revision = 'db7d8d0c4cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('is_internship', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_hackathon', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('stipend', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('prize_money', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('posted_date')
        batch_op.drop_column('company')
        batch_op.drop_column('package_max')
        batch_op.drop_column('max_experience')
        batch_op.drop_column('title')
        batch_op.drop_column('min_experience')
        batch_op.drop_column('package_min')

    with op.batch_alter_table('job_batches', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('batch_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_batches', schema=None) as batch_op:
        batch_op.alter_column('batch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('min_experience', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('max_experience', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('package_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('posted_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('deadline')
        batch_op.drop_column('prize_money')
        batch_op.drop_column('stipend')
        batch_op.drop_column('salary')
        batch_op.drop_column('is_hackathon')
        batch_op.drop_column('is_internship')
        batch_op.drop_column('role')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
