"""Initial migration

Revision ID: d8f9e92f4adf
Revises: 
Create Date: 2025-10-15 15:40:35.661985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f9e92f4adf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('apply_link', sa.String(length=500), nullable=False),
    sa.Column('is_internship', sa.Boolean(), nullable=True),
    sa.Column('is_hackathon', sa.Boolean(), nullable=True),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stipend', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prize_money', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('subscription_json', sa.Text(), nullable=False),
    sa.Column('batch_name', sa.String(length=10), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_notified', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_batch_name'), ['batch_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_endpoint'), ['endpoint'], unique=True)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_is_active'), ['is_active'], unique=False)

    op.create_table('job_batches',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'batch_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_batches')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_is_active'))
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_endpoint'))
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_batch_name'))

    op.drop_table('push_subscriptions')
    op.drop_table('job')
    op.drop_table('batch')
    op.drop_table('admin')
    # ### end Alembic commands ###
